apiVersion: v1
kind: Secret
metadata:
  name: notif-db-secret
type: Opaque
data:
  username: bm90aWYtYXBw #base64 для "notif-app"
  password: c2ltcGxlX3Bhc3N3b3Jk  #base64 для "simple_password"
  database: bm90aWZfZGI= #base64 для notif_db